### PR TITLE
Add tests for start/stop of Kafka server

### PR DESCRIPTION
**Pull request by Yuhu-kth**
all containers passed all tests
with linter/typechecker checked

### CODE REVIEW

**Comment by Yuhu-kth** [comment]
created topics using the cmds but I don't know how to check if topics are created

**Comment by Limmen** [comment]
You can do a similar call as shown here: https://github.com/Limmen/csle/blob/master/simulation-system/libs/csle-common/src/csle_common/controllers/kafka_controller.py#L138

This returns a KafkaDTO, which has the topics in a comma-separated string I think: https://github.com/Limmen/csle/blob/master/simulation-system/libs/csle-collector/protos/kafka_manager.proto#L24

**Comment by Yuhu-kth** [comment]
tried it, but after creating topics, the topics is still empty

**Comment by Limmen** [comment]
It should work, try debugging it and see why it does not create the topics. One thing you can try is that after you have started the server, sleep for 30s before you send a request to create topics.

**Pull request merged**
