### PR TITLE
add unit test for csle-common

### PR DESCRIPTION
**Pull request by foroughsh**

### CODE REVIEW

**Comment by foroughsh** [comment]
I add new function.

**Comment by foroughsh** [comment]
I add one more.

**Comment by foroughsh** [comment]
Last one for tonight :)

**Comment by Limmen** [comment]
> Last one for tonight :)

Thank you

**Review by Limmen — APPROVED** [review]

**Comment by foroughsh** [comment]
Thank you Mr :).

On 10 Sep 2023, at 21:20, Kim Hammar ***@***.***> wrote:



Last one for tonight :)

Thank you

**Pull request merged**
